### ISSUE TITLE
OCI login from golang client

### ISSUE THREAD

**Issue by eshneken** [hashicorp/vault-plugin-auth-oci#5]
What is the proper way to programmatically perform this function:

vault login -method=oci auth_type=instance role=vaultadminrole

in golang code?  I'm writing code that exercises the SDK like this:

config := &api.Config{
		Address: vaultAddr,
	}
	client, _ := api.NewClient(config)
        c := client.Logical()
	secret, err := c.Read("secrets/foo")
.
.
.

What is the correct way to login assuming that this code runs on a compute instance that has been properly set-up via dynamic groups?

**Comment by kalafut** [comment]
You can use the `Write()` method in the API with the required data. The `-output-curl-string` option for the CLI will show what it would have sent, which can be useful.

Note, please reserve the Github issues list for bugs reports and feature requests. The Vault discussion forum is a good place for general Q/A, since the community can help and also benefit from the dialog there:  https://discuss.hashicorp.com/c/vault
